name: todo_dart_react
version: 2.0.0
description: Dart + React Todo List Example
homepage: https://github.com/leerob/dart-react-todo
author: Lee Robinson <me@leerob.io>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  moor:
  over_react: ^2.0.0
  mobx:
#  w_flux: ^2.10.1
#  react: ^4.6.0

dev_dependencies:
  build_runner: ^1.5.2
  mobx_codegen:
  moor_generator:
    path: /Users/elvislee/workspace/dart/moor/moor_generator
  build_test: ^0.10.8
  build_web_compilers: ^2.1.1
  json_serializable:
#  coverage: ^0.12.4
#  dart_style: ^1.0.8
  over_react_test: ^2.4.0
  test: ^1.5.3

dependency_overrides:
  moor:
    path: /Users/elvislee/workspace/dart/moor/moor